created tabs with arrows
UofT-Frosh-Orientation/orientation-website pull request #115
Opened 2022-06-07 05:17 UTC by Emily9023

colors are not finished!! I couldn't find where the hex codes were but will be asking the team once I get the chance (prolly at the meeting)

I feel like there is definitely a better way of doing this so if anyone has an idea, pls shoot me a msg or comment on this pull request!!

2022-06-09 02:25 UTC, jameskokoska commented
When you get a chance please provide a Storybook

As per our previous convo, 

I always reference `Confetti.stories.jsx` it's a good example
```js
import React from 'react';

import { Confetti } from './Confetti';

export default {
  title: 'Confetti',
  component: Confetti,
};

export const ConfettiStory = (args) => <Confetti {...args} />;
ConfettiStory.storyName = 'Confetti';
ConfettiStory.args = {
  animate: true,
};
```

To create a story, create a file with `.stories.jsx` at the end
To view the story, in client, run `yarn storybook`

2022-06-11 22:50 UTC, jameskokoska requested changes
Looks good, maybe a few style changes and formatting fixes
Maybe add some rounded corners to the parent container
If the inner container (tab content) overflows, make it scrollable
Maybe make it a bit more obvious which tab is selected (use the ButtonSelector component)
![image](https://user-images.githubusercontent.com/50821962/173207165-60212009-5fef-4655-8d1f-dba5f85d7d0e.png)

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.Tabs-desktop {
Stick to lower case with dashes

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.test {
Remove unused CSS classes

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.inline-block {
Avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.relative {
Avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.footer {
avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.arrow-btn {
Avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.nav-btn {
Avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.btn-left {
Avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.btn-right {
Avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.scss
> +.icon_container {
use lower case with dashes
and avoid generic CSS names

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +                        <svg
Download and import the file locally
Use React Import asset

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +                        <svg
Download and import the file locally

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +          {/* <Dropdown
Remove unused code

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +  const items = ['Option 1', 'Option 2', 'Option 3'];
Remove unused code

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +                        <svg
download and import svg asset

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +                        <svg
download and import asset

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +const TabsDesktop = ({ tabs }) => {
I think keeping the same format for both web and mobile should be okay
It's generally bad practice to load/unload component from resizing
The desktop format should work okay on mobile no?

2022-06-11 22:50 UTC, jameskokoska commented on client/src/components/tabs/tabs.jsx
> +              <Button
You can use the `<ButtonSelector>` component that was recently made to handle the selection and styles for you

2022-06-12 01:20 UTC, jameskokoska commented
![image](https://user-images.githubusercontent.com/50821962/173210240-dfec6d3d-6d4f-4bf6-a797-11a94751775c.png)

2022-06-12 01:21 UTC, jameskokoska commented
@natapokie Could you change the colors of the arrows for me
I don't have illustrator on my laptop
```js
import ArrowRight from '../../assets/steps/arrow-right-solid.svg';
import ArrowLeft from '../../assets/steps/arrow-left-solid.svg';
```

2022-06-12 01:22 UTC, jameskokoska approved these changes

2022-06-12 01:23 UTC, jameskokoska commented
@Emily9023 Feel free to review these changes as well
You don't need to submit a proper Review since you own this PR

2022-06-12 03:52 UTC, natapokie approved these changes
Looks really good!! The tabs are so cool

2022-06-12 03:54 UTC, merged

2022-06-12 03:56 UTC, natapokie commented
Also @jameskokoska, I found out recently that you can actually change the colour of an svg file inside the file, so you don't need to use illustrator!

If you add `fill="#hexcode"` to the `<path` or `<polygon`, etc. you can colour the svg file! I just thought it was really cool, and wanted to share this!
![image](https://user-images.githubusercontent.com/86009011/173213660-2b52db2d-c9d2-4a7f-9ab8-3b74bebf4749.png)

2022-06-12 03:59 UTC, jameskokoska commented
oh ya that's useful
I just didn't do it on the ones from font awesome because that tag didn't exist to begin with
but good to know you can add it in!