92 timeline routes
UofT-Frosh-Orientation/orientation-website pull request #234
Opened 2022-06-30 19:50 UTC by Emily9023

- [x] a route to read a list of Timeline Date objects
(no permissions)
- [x] a route to change/edit a Timeline Date objects
- [x] a route to add a Timeline Date object
- [x] a route to delete a Timeline Date object
- [x] a route to change the order of a Timeline Date object 
(only certain accounts can do this) <- changed this to just sort the timeline by date

2022-07-01 04:22 UTC, Freeassassin requested changes
Honestly amazing work! Unfortunately, I couldn't get it to work on my machine ( empty documents and no changes with edit) but like it only took a couple of quick changes to get it to run, I commented the changes I made!

Also @Cali0707 told me to use a deleted flag instead of actually deleting stuff off of the database, so maybe also add that?

2022-07-01 04:22 UTC, Freeassassin commented on server/src/services/TimelineServices.js
> +  },
```suggestion
  async updateTimelineElement(id, date, name, description) {
    return new Promise((resolve, reject) => {
      TimelineModel.findOneAndUpdate({ _id: id }, {date, name, description}, (err, Timeline) => {
        if (err || !Timeline) {
          reject('UNABLE_TO_UPDATE_TIMELiNE');
        } else {
          resolve(Timeline);
        }
      });
    });
  },

  async saveNewTimelineElement(date, name, description) {
    return new Promise((resolve, reject) => {
      TimelineModel.create({date, name, description}, (err, newTimeline) => {
        if (err) {
          reject(err);
        } else {
          resolve(newTimeline);
        }
      });
    });
  },

```

2022-07-01 11:19 UTC, Cali0707 commented
@Freeassassin @Emily9023 don’t worry about using a deleted flag here - that is only really a thing for frosh data

2022-07-01 17:14 UTC, Freeassassin approved these changes
Looks great!

2022-07-04 13:38 UTC, Cali0707 commented
@Emily9023 can you resolve the merge conflicts here?

2022-07-05 01:44 UTC, Cali0707 approved these changes
This is great work!  I added comments about three very small stylistic changes, but I am going to merge and approve this anyways. Think about these as just future things to do

2022-07-05 01:44 UTC, Cali0707 commented on server/src/controllers/TimelineController.js
> +    const id = req.params.id;
```suggestion
    const {id} = req.params;

```

2022-07-05 01:44 UTC, merged