199 show popup to ask if they would like to discard all changes when editing fields
UofT-Frosh-Orientation/orientation-website pull request #235
Opened 2022-07-02 20:28 UTC by natapokie

- fixed navbar (and footer) bugs (#159 and #160)
  - highlights current page on navbar
  - prevents refreshing when on the same page (navbar and footer)
- added white checkmark (#184)
- also fixed some small style issues with navbar on mobile view

2022-07-02 21:56 UTC, NeoLou approved these changes
LGTM!

2022-07-05 22:25 UTC, jameskokoska requested changes
https://github.com/UofT-Frosh-Orientation/orientation-website/issues/160 isn't applied to the mobile navbar

other than that it's good to go

2022-07-05 23:20 UTC, natapokie commented
> #160 isn't applied to the mobile navbar
> 
> other than that it's good to go

Sorry i missed that! Should be good now, i also realized i forgot to apple #160 for the buttons, so I did that as well! (And I also deleted a prop for some reason, so I brought that back 😅)

2022-07-05 23:23 UTC, jameskokoska approved these changes

2022-07-05 23:23 UTC, merged