Add date when question was asked
UofT-Frosh-Orientation/orientation-website pull request #377
Opened 2022-07-25 03:07 UTC by NeoLou

added dateAsked and lastUpdated to faq model

2022-07-25 03:10 UTC, lukewarmtemp approved these changes
LGTM!

2022-07-25 15:38 UTC, Cali0707 requested changes
@NeoLou please read here: https://mongoosejs.com/docs/timestamps.html

This is an easier way to implement this functionality because it will allow us to not need to remember to update the lastUpdated field

2022-07-25 17:37 UTC, NeoLou commented
I changed the model to include timestamps to know the created date and updated date according to this documentation: https://mongoosejs.com/docs/timestamps.html

2022-07-26 01:15 UTC, Cali0707 requested changes

2022-07-26 01:15 UTC, Cali0707 commented on server/src/models/FaqModel.js
> +  { timestamps: true },
```suggestion
  { strict: true, timestamps: true },
```
For the options for a schema, they need to all be in the same object

2022-07-26 01:25 UTC, Cali0707 approved these changes

2022-07-26 01:25 UTC, merged