logic for scuntToken creation and user updates
UofT-Frosh-Orientation/orientation-website pull request #440
Opened 2022-08-02 21:37 UTC by Emily9023

user will have a token stored 
user inputs email and token on discord to log into scunt - if token and email match the records, then isLoggedInOnDiscord is set to true (default: false)

2022-08-14 19:04 UTC, Cali0707 requested changes
Overall this is good, just some changes need to be made to keep the code consistent with the rest of the codebase

2022-08-14 19:04 UTC, Cali0707 commented on server/src/services/UserServices.js
> +  async getScuntToken(email) {
It looks like this is adding a scunt token to a user. If that is the case, it should be renamed to reflect the fact that it is adding, not getting, a token for a user

2022-08-15 16:06 UTC, Emily9023 commented on server/src/controllers/ScuntController.js
> +        teamNumber: 'undefined', // existingUser.teamNumber
i think we havent established teamNumber yet for Users so its just a placeholder

2022-08-19 14:58 UTC, jameskokoska commented on server/src/controllers/ScuntController.js
> +        teamNumber: 'undefined', // existingUser.teamNumber
To be consistent with javascript either leave blank or set as undefined (not a string)

2022-08-22 23:46 UTC, Cali0707 requested changes

2022-08-22 23:46 UTC, Cali0707 commented on server/src/controllers/ScuntController.js
> +        teamNumber: 'undefined', // existingUser.teamNumber
@Emily9023 please update `teamNumber` to be `null` or `undefined` here if there is no number yet

2022-08-26 02:00 UTC, Freeassassin approved these changes
LGTM, just fix the one line!

2022-08-26 02:00 UTC, Freeassassin commented on server/src/services/UserServices.js
> +const getScuntToken = require('../middlewares/createScuntToken');
```suggestion
```

This is causing a crash in the backend.

2022-08-30 22:02 UTC, Cali0707 requested changes

2022-08-30 22:02 UTC, Cali0707 commented on server/src/controllers/UserController.js
> +    res.status(200).send(user.getResponseObject());
```suggestion
    let user = req.user;

    if (!(await UserServices.checkScuntToken(user))) {
      user = await UserServices.addScuntToken(user.email.toLowerCase());
    }

    res.status(200).send(user.getResponseObject());
```

2022-09-01 15:12 UTC, Cali0707 approved these changes

2022-09-01 15:12 UTC, merged