498 Ability to delete accounts
UofT-Frosh-Orientation/orientation-website pull request #509
Opened 2022-08-21 02:49 UTC by NeoLou

2022-08-22 03:40 UTC, natapokie approved these changes
looks great neo!! the functionality works as expected with frosh, leedurs and non-registered frosh!

i don't know if this is a bug, but you can actually delete the account that you're logged into, I think it's fine though haha

2022-08-22 23:40 UTC, Cali0707 requested changes
@NeoLou one small change and then this is ready to merge

2022-08-22 23:40 UTC, Cali0707 commented on server/src/services/UserServices.js
> +          reject('UNABLE_TO_DELETE_Timeline');
```suggestion
          reject('UNABLE_TO_DELETE_USER');
```

2022-08-23 00:49 UTC, NeoLou commented
@jameskokoska any other changes you think I should make?

2022-08-23 00:50 UTC, NeoLou commented
@Cali0707 made the change!

2022-08-28 23:26 UTC, jameskokoska commented
@natapokie could you do one final review and merge

2022-08-28 23:27 UTC, natapokie approved these changes

2022-08-28 23:29 UTC, natapokie commented
> @natapokie could you do one final review and merge

I think @Cali0707 needs to approve the requested changes first (?)

2022-08-28 23:31 UTC, jameskokoska commented
No problem, if it looks good to you then go ahead and merge it

2022-08-28 23:37 UTC, natapokie commented
> No problem, if it looks good to you then go ahead and merge it

merging is blocked 😅

2022-08-28 23:48 UTC, merged