Refractor frosh routes
UofT-Frosh-Orientation/orientation-website pull request #60
Opened 2022-05-26 22:59 UTC by lukewarmtemp

#23

2022-05-26 23:53 UTC, Cali0707 approved these changes
Looks great!

2022-05-28 15:47 UTC, NeoLou approved these changes
Looks good!

2022-05-30 23:27 UTC, Cali0707 requested changes
Just a few changes and this should be good to go -- great work!!

2022-05-30 23:27 UTC, Cali0707 commented on server/src/controllers/FroshController.js
> +//   },
Can you get rid of this commented-out code?

2022-05-30 23:27 UTC, Cali0707 commented on server/src/routes/froshRoutes.js
> +// router.put('/updatePasswordViaEmail', FroshController.updateFroshPassViaEmail);
Get rid of commented-out code

2022-05-30 23:27 UTC, Cali0707 commented on server/src/server.js
> +});
Thanks for fixing the order here -- looks great!!

2022-05-30 23:27 UTC, Cali0707 commented on server/src/services/FroshServices.js
> +  // },
Get rid of the commented-out code

2022-05-30 23:27 UTC, Cali0707 commented on server/src/services/FroshServices.js
> +  async initFroshGroups(groups) {
Please add a [jsdoc comment](https://jsdoc.app/about-getting-started.html) to document this function - all you need is a one sentence description, and then params and a return type

2022-06-07 13:23 UTC, Cali0707 commented
@lukewarmtemp any updates on the status of this?

2022-06-09 21:30 UTC, closed without merging