About Us Page Optimizations
UofT-Frosh-Orientation/orientation-website pull request #613
Opened 2023-06-01 05:34 UTC by vproHacks

## **Contribution:**

### **Issue:**

Closes #601 

### **Accomplishments:**

- Created a timeout on the `ExecProfile` component with a constant `EXEC_TIMEOUT` to configure how long it takes before defaulting
- Created a wrapper for the `AboutUsTeamTabs` component that now has the state variable `showAboutUs` to display or not (functionality shown with a simple toggle button)

### **Visuals:** 

Just used a default button

## **Details:**

### **Expected Behavior:**

- Upon clicking on a profile it should revert back to the photo in 5 seconds
- On clicking the toggle it should toggle displaying the team alongside maintaining the current tab.

### **Testing Steps:**

Steps required to get expected behavior.

- start the front end (no docker needed)
- Go to About page and scroll down to see the components

### **Complications:**

- Just getting used to Hooks and attempting to set timeout accurately in React

### **Resources:**

Any additional resources used outside this in issue.

- [Help with react timers](https://felixgerschau.com/react-hooks-settimeout/)

2023-06-01 16:45 UTC, vproHacks commented
Added the functionality for placeholder, ready for PR review.

2023-06-02 02:14 UTC, Tanushanth approved these changes
Tested out the timeout, times out after 5 seconds properly! Also, I tried making the showAboutUs state false to see how it looks and it works perfect :).

2023-06-02 05:08 UTC, natapokie requested changes
great work vraj! really nice use of the timeout, works great!

just a quick note on the overall logic of the code, my explanation probably wasn't clear and way the code runs is different than what I intended when I first wrote the issue...

- we want to use the "wrapper" so that it either displays the tab component or the "stay tuned" text, which is why I suggest using the ? operator in the `AboutUsTeamsTabWrapper`
- we want to display **certain** tabs depending on the active state (this is probably where I was being unclear). 
  - the main reason for this is that we might want to show only the execs and nothing else, or maybe we would want to show the execs and hls and no one else. 
  - we can easily comment out the code, but we want it to look a little cleaner and intentional, so we're introducing this new `active` state.
  - so there is no need to "update" the `tabs` array by setting active to true in the `AboutUsTeamsTabWrapper`, this changes the purpose behind the `active` field in the object
  
hope this makes more sense, I might also be testing your code wrong as well, I just couldn't find a way to only show one tab or two tabs for example. I've left suggestions for areas that you might want to look at and feel free to ask if you're still confused!!

2023-06-02 05:08 UTC, natapokie commented on client/src/pages/About/ExecProfile/ExecProfile.jsx
> +const EXEC_TIMEOUT = 5000;
nice use of the timeout!
for now lets set the timeout to 25s (or maybe 30s?), I know it's a little long but reading some of the exec profiles does take a while ahha

2023-06-02 05:08 UTC, natapokie commented on client/src/pages/About/About.jsx
> +      <AboutUsTeamsTab />
would recommend making use of the state here to check whether to display
`<h2 className="about-introduction-title">Stay tuned to meet the team!</h2>`
this is just makes the code a little cleaner and easier to follow since we're either displaying the tab component or the stay tuned text...

another note is that you can simply just use a variable `const showAboutUs` rather than a state, although both work!

you can do something like this with the use of a ternary operator...

```
return (
  <>
    {
      showAboutUs ?
      <Tab.. />
      :
      <Text />
    }
  </>
);
```

2023-06-02 05:08 UTC, natapokie commented on client/src/pages/About/About.jsx
> +  if (!showAboutUs) tabs.map((tab) => (tab.active = false));
you might want to remove this `if...else`, since it sets all the active fields to either true or false, we won't be able to hide/show specific tabs

2023-06-02 05:08 UTC, natapokie commented on client/src/pages/About/About.jsx
> +        <h2 className="about-introduction-title">Stay tuned to meet the team!</h2>
mentioned in the comment below, but this line is best returned in the `AboutUsTeamsTabWrapper`

2023-06-02 05:08 UTC, natapokie commented on client/src/pages/About/About.jsx
> +  if (tabs.every((value, index, array) => value.active))
you can remove this statement here... `if (tabs.every((value, index, array) => value.active))`, you're checking for `active` in the actual component, so I'm not entirely sure what this line does?

and I didn't realize until now, but you'll need to make adjustments to the state to `setCurrentTab` to the first tab that is active! you can use a `useEffect`, with an empty dependency array, `[]` so it executes on first render

2023-06-02 17:39 UTC, vproHacks commented on client/src/pages/About/ExecProfile/ExecProfile.jsx
> +const EXEC_TIMEOUT = 5000;
Changed to 25s!

2023-06-02 17:39 UTC, vproHacks commented on client/src/pages/About/About.jsx
> +      <AboutUsTeamsTab />
Added Ternary with constant instead of state

2023-06-02 17:40 UTC, vproHacks commented on client/src/pages/About/About.jsx
> +  if (!showAboutUs) tabs.map((tab) => (tab.active = false));
moved to wrapper and changed functionality for specific tab use

2023-06-02 17:41 UTC, vproHacks commented on client/src/pages/About/About.jsx
> +  if (tabs.every((value, index, array) => value.active))
Created a default first element by only checking for wanted tabs done without using effect since that would be expensive for each render.

2023-06-02 17:45 UTC, vproHacks commented
Added a new variable `wantToLoad` for each tab that controls if that tab is to be loaded. If true then the tab will be loaded, otherwise it will not be rendered.

2023-06-03 03:16 UTC, natapokie approved these changes
great job vraj! 
thanks for making these changes, sorry for the unclear instructions in the beginning, hope the changes didn't take too much time!!

2023-06-03 03:16 UTC, merged