600 sponsor layout change
UofT-Frosh-Orientation/orientation-website pull request #618
Opened 2023-06-04 05:18 UTC by uzFer

## **Contribution:**

### **Issue:**
Closes #600 

### **Accomplishments:**
- Added 'View Less' button that sends you back into carousel view for sponsors by editing Home.jsx -> HomePageSponsors. Added another button and set corresponding `setViewAll` variable to false on click.
- Made all sponsor images in the carousel have the same size by editing ImageCarousel.jsx and ImageCarousel.scss - there was some inline styling in the `carousel-slide-container` using the 'transform' property that made each image different sizes
- Added mesh gradient borders for each sponsor in carousel view (only middle one's border is shown)
   - Created another field in sponsors.jsx for the 'rank', used this for inline CSS styling for each item in the carousel
   - Added each mesh gradient (bunch of radial-gradients combined) into colors.jsx

### **Visuals:** 
'View Less' button: 
![image](https://github.com/UofT-Frosh-Orientation/orientation-website/assets/109243682/9fc05f83-7d56-457c-b6be-9a64e259903b)

Image Carousel (Diamond, Gold, Bronze):
![image](https://github.com/UofT-Frosh-Orientation/orientation-website/assets/109243682/98bee9d0-9f78-4712-9ed6-c87c4e41b178)
![image](https://github.com/UofT-Frosh-Orientation/orientation-website/assets/109243682/c62b21bd-4fcd-4ef0-9dce-bbe65d0df236)
![image](https://github.com/UofT-Frosh-Orientation/orientation-website/assets/109243682/76c6310d-ddd7-46a2-9dbb-4b11f8d3d33e)

## **Details:**

### **Expected Behavior:**
- 'View Less' button should collapse 'all sponsors' viewing and send user back to carousel view
- Sponsor images should be of same size and have visual indication of the rank (bronze, diamond, gold, etc.) from their border

### **Testing Steps:**

Steps required to get expected behavior:
- Just run the front end and scroll down on the homepage to the sponsor carousel

### **Complications:**
- Mesh gradients finally worked in the borders somewhat, not sure if it works in mobile view though since I had some laptop issues as well
- I wasn't sure how to include all the radial-gradients in separate lines in the colors.jsx file, so they're just these huge lines right now: 
![image](https://github.com/UofT-Frosh-Orientation/orientation-website/assets/109243682/dc8d0ab6-d82a-4eec-899d-ecd8c3662a13)
- I also made the 'no rank' sponsors just have a white border, but if there's a preferred colour for that, I can add it! Let me know if other colours should be changed as well

### **Resources:**

Any additional resources used outside this in issue.

- Linear gradient maker: [https://cssgradient.io/](url)
- Mesh gradient maker (courtesy of Natalie): [https://csshero.org/mesher/](url)

2023-06-06 11:24 UTC, Sherryzh0830 commented
Great job! Everything works as described. Just one comment/suggestion on the color of borders: It is a little confusing for the white ones without rank in carousel view as I initially mistook it as silver or something else. Maybe no need to add any colors for those ones? Or some color that is more transparent?

2023-06-06 11:26 UTC, Sherryzh0830 approved these changes
Great job! Everything works as described. Just one comment/suggestion on the color of borders: It is a little confusing for the white ones without rank in carousel view as I initially mistook it as silver or something else. Maybe no need to add any colors for those ones? Or some color that is more transparent?

2023-06-10 21:07 UTC, natapokie requested changes
great work uzma! just made some small comments in the code...

and one last task for you before closing up this issue... since you're adding some new features to the sponsors page, we'd like you to add a little bit of documentation under `docs\pages\Project Architecture`, just so people know how to use it in the future!

just a quick intro to the documentation, it's pretty much a markdown (.md), and once you commit, it will show up [here](https://docs.orientation.skule.ca/).

You can add a new file called `Sponsors.md`, and include the following at the top,
```
---
layout: default
title: Sponsors
parent: Frontend
---
```
this code snippet pretty much nests the page under Frontend.md, you will also have to add the following line to this file... `docs\pages\Project Architecture\Frontend.md`
```
has_children: true
```
check out the "docs" [documentation](https://just-the-docs.com/docs/navigation-structure/#example-2:~:text=the%20main%20navigation.-,Pages%20with%20children,-Sometimes%20you%20will) for more info!

some things to include in the documentation...
- the structure of the sponsors object
  - what each of the properties control
- how the rank works and where the style is located (in case we ever need to change it in the future)

2023-06-10 21:07 UTC, natapokie commented on client/src/components/ImageCarousel/ImageCarousel.scss
>    background-color: var(--sponsor-background);
small issue in light mode probably caused by this?
![image](https://github.com/UofT-Frosh-Orientation/orientation-website/assets/86009011/283f7911-a8d9-40db-856c-98b02b8bc552)
this variable is probably set to transparent in light mode, so if you could change that to white (#ffffff) in the colors.jsx file, or even better we can just change, 
`background-color: var(--white)` !

2023-06-10 21:07 UTC, natapokie commented on client/src/util/sponsors.jsx
>      website: 'https://alumni.engineering.utoronto.ca/engineering-alumni-network/',
and for now can you comment out all the sponsors as well? just make sure it looks like this!
this way we are ready to show our website to new sponsors!
```
export const sponsors = []
```

2023-06-10 21:07 UTC, natapokie commented on client/src/pages/Home/Home.jsx
> +        <Button
can you also add a condition for the Button component (View All and View Less) so that when there are no sponsors (list is empty), the button doesn't show?

2023-06-10 21:12 UTC, natapokie commented
also forgot to reply to some of your complications!
- mobile looks good!
- no worries about the long lines of CSS ahahha
- a white border for 'no rank' is good

2023-06-12 14:19 UTC, natapokie approved these changes
great work uzma! thanks for adding in those changes!

2023-06-12 14:19 UTC, merged