621 confirming emails when creating accounts
UofT-Frosh-Orientation/orientation-website pull request #630
Opened 2023-06-11 20:11 UTC by uzFer

## **Contribution:**

### **Issue:**
Closes #621 

### **Accomplishments:**
- Edited Sign Up page to tell users to check inbox for a verification link.
- Added 'confirmed' flag in `UserModel.js` which checks if they verified their account through email token or not
- Sends email token upon signing up using EmailServices.js. Instead of making a new function in `UserServices.js,` I tried to  update createUser so that an email is sent after creating an account. 
- Updated `userRoutes.js` with a route to confirmUser in `UserController.js`. This employs the validateEmailConfirmationToken function in `UserServices.js` to check the token and change the flag accordingly.
- Included another condition to the login function in `UserController.js` so that unconfirmed users should not be able to log in
- Created new page called `EmailConfirmed.jsx` to display status after the email token is sent. This should show a 'Perfect' or 'Oh no' message and have a button to let users log in again.

### **Visuals:** 
(I'll update once Docker works again)
**Error message:** 
![image](https://github.com/UofT-Frosh-Orientation/orientation-website/assets/109243682/ca072edf-cb41-40e6-839a-bee08bfd3eb4)

## **Details:**

### **Expected Behavior:**
- You should be able to sign up normally. The message after submitting the sign up form should tell you to check your inbox.
- An email with a URL should be sent (can't guarantee it working yet) that you can click to verify your account.
- Your account should then be confirmed if done correctly and you will be prompted to log in again. Otherwise, you will get an 'Oh no' message and have a button to try signing up again.

### **Testing Steps:**
Steps required to get expected behavior:
- Set `readyForFrosh = true`
- Run the backend using `docker-compose --up build`
- Head to the login page --> Create account
- Put in valid email address and info, check your inbox, click the link, and see if your account was confirmed correctly. You can also put invalid ones and check if you are able to login, too.

### **Complications:**
- Had some problems with committing, I need to check if it added the right files.
- I had issues with just running Docker recently, so I haven't been able to test this task properly. 

### **Resources:**
Any additional resources used outside this in issue.
- For my committing issues: `https://github.com/typicode/husky/issues/1038`

2023-06-12 05:24 UTC, Tanushanth commented
Works perfectly, I tested with the frosh account and Leedur accounts, and the email comes through correctly. 
Just one small thing which I'm not sure how it would be implemented, but the first time when you sign up and it tells you to check your email, you are already logged in. Afterward, it won't let you in without verifying so thats fine.
Other than that it's all good!

2023-06-12 05:24 UTC, Tanushanth approved these changes
Works perfectly, I tested with the frosh account and Leedur accounts, and the email comes through correctly.
Just one small thing which I'm not sure how it would be implemented, but the first time when you sign up and it tells you to check your email, you are already logged in. Afterward, it won't let you in without verifying so thats fine.
Other than that it's all good!

2023-06-12 16:11 UTC, Freeassassin requested changes
Hey Uzma, overall great work! The functionality is all there and everything works properly. However, there are a couple of things I need you to take care of:

- [x] Currently after you sign up you still get logged in automatically. This is because of how sign-up works in the `/state/user/saga.jsx` file. Edit the files in `state/user/` to separate signup from sign in by adding to the `useSlice.jsx` the following `singupStart`, `singupSuccess`, `singupFail`. 
- [ ] In the backend instead of sending the email in services files do it through the `newUserSubcription.js`. This will make sure that the backend will be able to send a response and take care of the email later. For reference look at how it is done in `requestPasswordReset()`. Additionally, make sure that the sign up email is sent after the email confirmation has been completed.  


Feel free to reach for more clarification.

2023-06-12 16:11 UTC, Freeassassin commented on client/src/pages/EmailConfirmed/EmailConfirmed.jsx
> +      console.log(e);
Dont use console.log() here, instead if it is a user facing error use the `setSnackbar` component.

2023-06-12 16:11 UTC, Freeassassin commented on client/src/pages/SignUp/SignUp.jsx
> +                </Link> */}
Remove extra comments.

2023-06-12 16:11 UTC, Freeassassin commented on server/src/controllers/UserController.js
> +      //});
Remove extra comments.

2023-06-16 03:44 UTC, Tanushanth commented
Tested again, it works one after the other now.

2023-06-16 16:17 UTC, Freeassassin approved these changes
Hey Uzma, everything is great! Thank you for your time and effort on this issue! Just make sure to take care of your merge conflicts 👍

2023-06-16 16:17 UTC, Freeassassin commented on server/src/services/LeadurServices.js
>  const newUserSubscription = require('../subscribers/newUserSubscription');
Get rid of the unused imports.
```suggestion
const LeadurModel = require('../models/LeadurModel');
```

Remove unused imports.

2023-06-16 18:06 UTC, merged