626 optimize profile page using dynamic imports
UofT-Frosh-Orientation/orientation-website pull request #647
Opened 2023-06-25 04:45 UTC by uzFer

## **Contribution:**

### **Issue:**
Closes #626 

### **Accomplishments:**
- *Not finished*
- Was able to split the code into two files: `PageProfileFrosh.jsx` and `PageProfileLeedur.jsx`
- Got rid of most `if(leedur === true)` checks in the components
- Changed the header components so that they dont have a boolean leader variables as props, made them specific to leedur and frosh

### **Visuals:** 
Haven't been able to run it yet :p

## **Details:**

### **Expected Behavior:**
- You should just be able to run both Frosh and Leedur accounts as normal
- All components should work including header, schedule, scunt team/token, etc.

### **Testing Steps:**

Steps required to get expected behavior.
- Run docker
- Sign up or log in as either frosh or leedur accounts
- Access the Profile page and see if any component is missing

### **Complications:**
- Was not able to run it properly (even with just frontend) because I kept getting this error `line 8: C:\Users\uzmaf\AppData\Roaming\npm/node_modules/node/bin/node: No such file or directory` - still trying to figure it out
- Couldn't do the dynamic importing for some reason, there was an error with it when Tanu tested it for me
- The `PageProfileFrosh.jsx` and `PageProfileLeedur.jsx` are still pretty long files with ~900 lines of code
- Had to change some imports from other files like `ScuntHome.jsx` and `ProfileEdit.jsx`

### **Resources:**
- Soon to come once I can run it

2023-07-06 03:54 UTC, natapokie requested changes
great work on separating all the components uzma! 

i merged the branch with dev, so you have the updated version (thought it would be easier since i could run docker ahha)!

as for dynamic loading, you can try using this package that's already installed called.... [react-lazy-load-image-component](https://www.npmjs.com/package/react-lazy-load-image-component), and you can use `LazyLoadComponent` tag, I'm honestly not sure if it actually helps with performance, but we use the same lazy loading for images so i thought it might be good to try!

As for splitting up the components more, I got started on a few components that were integrated with the backend... You can use the folder under components called profile, made a few as a template that you can follow!

For components like resources and schedule, since used in both frosh and leedur profiles (they should be frontend stuff only too), it would be great if you can put them in separate components!

(Also I think i left a ton of commented-out code, so if you notice anything please help me delete, thanks!!)

2023-07-06 03:54 UTC, natapokie commented on client/src/components/profile/ProfilePageResources/ProfilePageResources.jsx
if you can add the resources and schedule as a separate component since they're used for both leedur and frosh pages!

2023-07-06 03:54 UTC, natapokie commented on client/src/util/pages.jsx
> -    //   {
uncommented this for now!

2023-07-06 03:54 UTC, natapokie commented on server/src/controllers/UserController.js
just want to confirm that the UserController and UserServices is part of the pr or whether it's from the email confirmation pr?

2023-07-06 20:10 UTC, uzFer commented on server/src/controllers/UserController.js
should be just from the email confirmation pr, I see those files were changed here too - don't remember why I did but probably a spacing or console.log thing. Also changed the sponsors.md documentation file because I noticed a typo I made from before

2023-07-07 04:00 UTC, natapokie commented on server/src/controllers/UserController.js
ok sounds good! just wanted to check, will resolve this convo

2023-07-09 00:20 UTC, natapokie approved these changes

2023-07-09 21:54 UTC, Tanushanth approved these changes
All good! I tried with leader and normal accounts and everything comes up file on the profile page, only thing, I had to add this at the top of LeedurServices (but it exists in the main branch so not sure if we need to worry abt it) 

const emailConfirmationSubscription = require('../subscribers/emailConfirmationSubscription');

2023-07-10 05:35 UTC, Freeassassin approved these changes
Great work!

2023-07-10 05:35 UTC, merged