loading animation with css only
UofT-Frosh-Orientation/orientation-website pull request #72
Opened 2022-05-31 18:17 UTC by NeoLou

2022-06-01 22:01 UTC, Cali0707 commented
@NeoLou I am going to convert this to a draft while you work on removing the bootstrap code

2022-06-06 21:39 UTC, jameskokoska requested changes
Seems like there are some errors with the storybook

2022-06-07 21:13 UTC, natapokie commented on client/src/components/misc/LoadingAnimation/LoadingAnimation.scss
> +/* Remove everything under this to stop logo spinning */
yep, just remove the spinning logo part! it might just be me, but I get dizzy looking at it 😂

2022-06-07 21:15 UTC, natapokie approved these changes
looks good! i like the dino test icon 😂

2022-06-10 21:05 UTC, jameskokoska approved these changes

2022-06-10 21:06 UTC, merged