added task announcement component
UofT-Frosh-Orientation/orientation-website pull request #90
Opened 2022-06-01 04:34 UTC by jameskokoska

![image](https://user-images.githubusercontent.com/50821962/171328321-4ec2be4e-65d3-4344-bb37-479a82948bc1.png)

2022-06-01 15:01 UTC, natapokie commented on client/src/components/task/TaskAnnouncement/TaskAnnouncement.scss
> +  transition: outline 500ms, box-shadow 500ms, background-color 500ms, transform 500ms;
```suggestion
  box-sizing: border-box;
  background-color: var(--green-success);
  width: 56px;
  height: 56px;
  flex-shrink: 0;
  margin: 0px 0px 0px 20px;
  border-radius: 15px;
  border: 2px solid var(--green-success);
  transition: border 500ms, box-shadow 500ms, background-color 500ms, transform 500ms;
```

2022-06-01 19:42 UTC, jameskokoska commented
@natapokie donezo!
![image](https://user-images.githubusercontent.com/50821962/171488344-a755ba43-ba8b-4654-9daf-7e9bd3af317e.png)

2022-06-01 22:06 UTC, Cali0707 requested changes
@jameskokoska can you add a function for `onUnComplete`? There may be a case where someone accidentally checks a task off, and we would want to be able to handle the logic for that separately

2022-06-03 14:14 UTC, jameskokoska commented
Going to merge, need check image for checkbox component

2022-06-03 14:14 UTC, merged