created accordion component with animation
UofT-Frosh-Orientation/orientation-website pull request #91
Opened 2022-06-01 05:10 UTC by lukewarmtemp

#31 

Couldn't figure out initialOpen with the current way I'm doing the animations, but I can revisit it's something important that we really need. Accordion opens both with onClick() and whenever the toggle prop value changes. Note: open/closed state is independent of what the value is set to. Can make an adjustment to open/close corresponding to toggle=true/false but some changes also need to be made in onClick() function to ensure that we don't have a case where the accordion is closed but toggle is set to true and vice versa.

2022-06-01 05:13 UTC, lukewarmtemp commented
Also, I'll get the images of what it looks/prove that it's working sometime tomorrow

2022-06-01 19:49 UTC, jameskokoska requested changes
Looks good though!

2022-06-01 19:49 UTC, jameskokoska commented on client/package.json
> +    "@fortawesome/fontawesome-svg-core": "^6.1.1",
For icons, download the svg you want to use and import it
It reduces package count

2022-06-01 19:49 UTC, jameskokoska commented on client/src/components/Accordion/SingleAccordion/SingleAccordion.jsx
> +const SingleAccordion = ({ header, children, toggle }) => {
For initial value, pass in a prop `isInitiallyOpened`
and in the line below do  `const [isActive, setActive] = useState(isInitiallyOpened ? 'active' : 'closed');` for example
This initially opened might be needed for UX to show users that the accordion can be opened (by leaving one opened by default)

2022-06-02 19:50 UTC, lukewarmtemp commented
Removed the packages for font-awesome and downloaded the SVG for the arrow button. Made it such that the isOpen state and setIsOpen needs to passed from the parent function as props. Makes the code cleaner in the component and serves as a dual purpose for isInitallyOpen because we can pass isOpen = true/false.

2022-06-02 21:15 UTC, jameskokoska submitted a review, later dismissed
Looks good!

2022-06-02 22:56 UTC, Cali0707 approved these changes
Looks good, there are two minor spelling mistakes, but I don't think those really matter.

2022-06-02 22:56 UTC, Cali0707 commented on client/src/components/Accordion/SingleAccordion/SingleAccordion.jsx
> +    <div className="accordian" onClick={toggleAccordion}>
fix the class name to be spelled properly

2022-06-02 22:56 UTC, Cali0707 commented on client/src/components/Accordion/SingleAccordion/SingleAccordion.scss
> +.accordian {
fix classname to be spelled properly

2022-06-02 22:59 UTC, merged